### ISSUE TITLE
Fix printing of allergies upon show details

### ISSUE THREAD

**Issue by yuki-zmstr** [AY2324S2-CS2113-W14-2/tp#117]
<img width="333" alt="Screenshot 2024-04-04 at 5 05 35 PM" src="https://github.com/AY2324S2-CS2113-W14-2/tp/assets/72074553/5df0b866-1128-4f03-a8c0-11b89a15cbe9">

**Comment by yuki-zmstr** [comment]
perhaps separate by comma

**Comment by nidhi-nayak** [comment]
already coded a fix for this! pushed it in my first PR! but since that one did not end up getting merged, i will do it in my next one.
