### ISSUE TITLE
Suggest user to input full word when filtering by allergies

### ISSUE THREAD

**Issue by yuki-zmstr** [AY2324S2-CS2113-W14-2/tp#118]
<img width="470" alt="Screenshot 2024-04-04 at 5 07 16 PM" src="https://github.com/AY2324S2-CS2113-W14-2/tp/assets/72074553/c5db5a88-a2f6-4389-9840-6470de3c6213">

**Comment by yuki-zmstr** [comment]
This print statement can be there, even if matches are found.

e.g. "Tip: input as a whole word"

**Comment by nidhi-nayak** [comment]
Is this needed or is it more intuitive? (example, technically the name and even inputted allergies and everything have to be legitimate strings, but i don't think we have to necessarily say so, just for cleanness of the output console.) what does everyone else think though? @chenxk619 @PDHung1104 @yuki-zmstr
