### ISSUE TITLE
[PE-D][Tester B] Large integers accepted for preparation time

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W14-2/tp#124]
![image.png](https://raw.githubusercontent.com/paturikarthik/ped/main/files/2a18e918-7e54-438a-af7b-346900e7f4b1.png)

We should expect some form of exception or warning that the timing is unrealistic.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: paturikarthik/ped#4

**Comment by nidhi-nayak** [comment]
should add java's max int limit
