### ISSUE TITLE
Fix build error caused by RecipeIOTest

### ISSUE THREAD

**Issue by yuki-zmstr** [AY2324S2-CS2113-W14-2/tp#15]
https://github.com/AY2324S2-CS2113-W14-2/tp/blob/99edf6fe79667642caeb871f2358f46c0e7593c3/src/test/java/recipeio/RecipeIOTest.java#L31

Hi Nidhi, please fix the build error here - it's probably a good idea to run the app locally first and check that it builds before pushing the branch and creating a PR, thanks!

**Comment by nidhi-nayak** [comment]
Yep, totally agree. So sorry! It was running on my device locally, but when fixing the merge conflict on github, I think I accidentally deleted a brace, and couldn't test it again. Will be more careful from now on! Thanks so much for catching it!
