### ISSUE TITLE
[PE-D][Tester A] Incorrect command format accept

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W14-2/tp#150]
![image.png](https://raw.githubusercontent.com/HenryGan138/ped/main/files/084d7559-38b5-445f-aad3-86462956b646.png)
Similar to list, help command has the same issue.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: HenryGan138/ped#9

**Comment by nidhi-nayak** [comment]
@chenxk619 Did you resolve one similar to this?
