### ISSUE TITLE
To clarify try catch block in AddRecipeCommand

### ISSUE THREAD

**Issue by yuki-zmstr** [AY2324S2-CS2113-W14-2/tp#76]
To clarify if we need this try-catch block

<img width="550" alt="Screenshot 2024-03-29 at 8 25 47 PM" src="https://github.com/AY2324S2-CS2113-W14-2/tp/assets/72074553/e14e85ef-917c-40d5-a15f-446b9de2ea90">

**Comment by yuki-zmstr** [comment]
Similar to Issue #79

**Comment by nidhi-nayak** [comment]
I just added this try-catch in case there is some issue with saving file (instead of the program shutting down, it should print an error saying it failed to save) -> increases usability. i think it serves some purpose (unlike the last one of MAX_RECIPES, but do you think different?)
