### ISSUE TITLE
Clarify allergy is singular or plural

### ISSUE THREAD

**Issue by yuki-zmstr** [AY2324S2-CS2113-W14-2/tp#80]
<img width="578" alt="Screenshot 2024-03-29 at 10 57 27 PM" src="https://github.com/AY2324S2-CS2113-W14-2/tp/assets/72074553/58378875-e448-442d-95f6-3423da98bea5">

**Comment by yuki-zmstr** [comment]
Do we want the filter command to recognize by full word only?

If so, we should make it explicit to the user whether to input allergies as singular or plural, and handle exceptions accordingly.

**Comment by nidhi-nayak** [comment]
if 0 matches, add the suggestion of missing plural (ie if lookup by egg -> maybe missing eggs)
