### ISSUE TITLE
Extract validation of Find class out from the FindCommand Class

### ISSUE THREAD

**Issue by yuki-zmstr** [AY2324S2-CS2113-W14-2/tp#96]
Could you see how the validation of the find method can be moved away from the Find Class?

Right now the validation is within the Find Class, because of the branching that is done there.

You could consider splitting the Find by keyword and by date into separate classes.

Currently, the rest of the methods have validation outside of the class, which is clean in terms of separation of concerns.

**Comment by nidhi-nayak** [comment]
@PDHung1104 extract FindbyCategory command
@nidhi-nayak extract FindDate command and FindKeyword command and general find command
